---
title: "Measles and Rubella Modelling Workshop"
output: html_document
---

[GOOGLE DOC TO ADD YOUR PROJECT QUESTIONS](https://docs.google.com/document/d/1ByohgaUithjij1el4xC91xxnM9s8zN0P0aJ-uwwumwE/edit)


**Mon, Feb 5**

* 08:45-09:00: Introduction _(Prof. Siuli Mukhopadhyay)_
* 09:00-09:45: Country's big leap towards measles and rubella elimination _(Dr. Pawan Kumar)_
* 09:45-10:15: Congenital rubella surveillance _(Dr. Manoj Muhrekar)_
* 10:15-10:30: *Tea Break*
* 10:30-11:00: Sub national level measles modeling and results _(Prof. Siuli Mukhopadhyay, Dr Divya Kappara, and Dr Sagar Pandhare)_
* 11:45-12:00: Introduction of participants
* 12:00-13:00: [Block 0.1: Epidemiology 101 terms and concepts used in this workshop](workshop_materials/block0.1_epi101.pdf) _(Mark Jit)_
* 13:00-14:00: *Lunch*
* 14:00-15:30: [Block 0.2: Introduction of ID models](workshop_materials/block0.2_introID.pdf) _(Amy Winter)_
* 15:30-15:45: *Tea Break*
* 15:45-17:15: [Block 1.1: History and current understanding of measles and rubella-specific dynamics](workshop_materials/block1.1_mark.pdf) _(Mark Jit)_

    Block 1.1 Interactive sessions:
    [SIR](workshop_materials/SIRModel 1base.r) | [SIR + births and deaths](workshop_materials/SIRModel 2birthsdeaths.r) | [SIR + vaccination](workshop_materials/SIRModel 3birthsdeaths vaccine.r)



**Tue, Feb 6**

* 09:00-09:30: Results of measles-rubella serosurveys in different states of India _(Dr Nivedita Gupta)_
* 09:30-10:00: National update on measles and rubella elimination _(Dr. Ratnesh Murugan)_
* 10:00-10:15: *Tea Break*
* 10:15-10:45: Spatial analysis and correlates of zero-dose measles vaccine prevalence in India _(Prof. Rama Pal, Dr Divya Kappara, Ms. Anshika Tiwari)_
* 11:15-12:15: Block 1.1: History and current understanding of measles and rubella-specific dynamics continued _(Mark Jit)_
* 12:15-13:00: [Block 1.2: History and current understanding of measles and rubella-specific dynamics - SIR Dynamics](workshop_materials/block1.2_matt.pdf) _(Matt Ferrari)_

    Block 1.2 Interactive sessions:
    [SIR + births and deaths + seasonality](workshop_materials/SIRModel 2birthsdeaths_seasonality.r) | [SIR + births and deaths + seasonality + RI](workshop_materials/SIRModel 2birthsdeaths_seasonality_vaccination.r) | [SIR + births and deaths + seasonality + RI + SIA](workshop_materials/SIRModel 2birthsdeaths_seasonality_vaccination_SIA.r)
* 13:00-14:00: *Lunch*
* 14:00-15:15: Block 1.2: History and current understanding of measles and rubella-specific dynamics - SIR Dynamics continued _(Matt Ferrari)_
* 15:15-15:30: *Tea Break*
* 15:30-17:15: [Block 1.3: History and current understanding of measles and rubella-specific dynamics - Age Effects on Dynamics](workshop_materials/block1.3_emilia.pdf) _(Emilia Vynnycky)_

    Block 1.3 Interactive sessions:
    [Berkeley Madonna Code](workshop_materials/block1.3_code.zip)



**Wed, Feb 7**

* 09:00-09:30: [Recap](workshop_materials/midworkshop_recap.pdf) _(Matt Ferrari)_
* 9:30-10:30  [Block 2.1: Model Fitting Approaches and Challenges - Catalytic Model](workshop_materials/block2.1_catalytic.pdf) _(Amy Winter)_

    Block 2.1 Interactive sessions:
    [Catalytic Model Code](workshop_materials/block2.1_catalytic_OLS.R) | [Rubella Serological Data](workshop_materials/rubella.sero.csv)

* 10:30-10:45: *Tea Break*
* 10:45-12:00: [Block 2.2: Model Fitting Approaches and Challenges - Dynamic Models and Probability](workshop_materials/block2.2_niket.pdf) _(Niket Thakkar)_

    Block 2.2 Interactive sessions:
    [Linear Regression Example](workshop_materials/block2.2_LinearRegressionExample.py) 
    [Block 2.2 slides with pseudocode answers](workshop_materials/block2_niket_withanswers.pdf)
    
* 12:00-13:00: [Block 2.3: Model Fitting Approaches and Challenges - Stochastic Simulation Algorithms](workshop_materials/block2.3_stochastic.pdf) _(Matt Ferrari)_

    Block 2.3 Interactive sessions:
    [Stochastic Simulation](workshop_materials/block2.3_stochastic.R) 
    
* 13:00-14:00: *Lunch*
* 14:00-15:15: [Block 2.4: Model Fitting Approaches and Challenges - TSIR Model](workshop_materials/block2.4_tsir.pdf) _(Niket Thakkar)_

    Block 2.4 Interactive sessions:
    [Somalia TSIR](workshop_materials/SomaliaTSIR_example.zip) | [UK TSIR](workshop_materials/UKtsir_example.zip)
    
* 15:15-15:30: *Tea Break*
* 15:30-17:15: Block 2.4: Model Fitting Approaches and Challenges - TSIR Model continued _(Niket Thakkar)_


**Thu, Feb 8**

* 09:00-09:15: Recap Block 2
* 09:15-10:15: [Block 3.1: Strategic Modelling and Impact Assessment](workshop_materials/block3_pico.pdf) _(Amy Winter)_
* 10:15-10:30: *Tea Break*
* 10:30-11:15: [Block 3.1: Interactive Session](workshop_materials/block3_interactive.zip)  _(Matt Ferrari)_
* 11:15-12:30: Block 3.2: VIMC Models _(VIMC Modellers)_
* 12:30-13:00: Participant Projects and Modelling Questions
* 13:00-14:00: *Lunch*
* 14:00-15:15: Group or one on one meetings
* 15:15-15:30: *Tea Break*
* 15:30-16:45: Group or one on one meetings
* 16:45-17:15: Closing Thoughts 


**Additional Materials**

[Data Analysis Textbook by Sivia](workshop_materials/sivia.pdf)
